name: build-and-push-docker-image

on:
    push:
        branches: ['main']
env:
    RUNNER_VERSION: v2.318.0
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IMAGE: ${{ github.repository }}

jobs:
    build-push-docker-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: checkout the repo
              uses: actions/checkout@v2
              
            - name: login to ghcr.io
              uses: docker/login-action@v2
              # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ${{ env.GITHUB_REGISTRY }}
              with:
                registry: ${{ env.GITHUB_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUBTOKEN }}
                
            - name: Build the Dockerfile
              run: docker build -t ghcr.io/anilnair00/package:${{ github.ref_name }} --build-arg RUNNER_VERSION=${{env.RUNNER_VERSION}} .
        
            - name: Push to GitHub Container Registry
              run: docker push ghcr.io/anilnair00/package:${{ github.ref_name }}
        
            # - name: extract the metadata (tags, labels)
            #   id: meta
            #   uses: docker/metadata-action@v5
            #   with:
            #     images: ${{ env.GITHUB_REGISTRY }}/${{ env.DOCKER_IMAGE }}      
                
            # - name: build-push-docker-image
            #   uses: docker/setup-buildx-action@v1
            #   with:
            #     context: ./file
            #     push: true
            #     tags: ${{ steps.meta.outputs.tags }}
            #     labels: ${{ steps.meta.outputs.labels }}
